#!/usr/bin/env ruby

$LOAD_PATH.unshift(File.dirname(__FILE__) + '/lib')

require 'ib_estonia'
require 'exchange_rate_fetcher'

unless ARGV[0]
  puts "Usage: ./start confirms-2016.xml confirms-2017.xml ..."
  exit 1
end

exchange_rate_fetcher = ExchangeRateFetcher.new

trades = ARGV.reduce([]) do |acc, path|
  puts ">> Importing #{path}"
  data = File.read(path)
  acc + IbEstonia::Importer.import(data, exchange_rate_fetcher)
end

report = IbEstonia::TaxReport.new(trades)
report.print
