#!/usr/bin/env ruby

$LOAD_PATH.unshift(File.dirname(__FILE__) + '/lib')

require 'ib_estonia'
require 'exchange_rate_fetcher'

unless ARGV[0]
  puts "Usage: ./start 2017.xml"
  exit 1
end

data = File.read(ARGV[0])
exchange_rate_fetcher = ExchangeRateFetcher.new
trades = IbEstonia::Importer.import(data, exchange_rate_fetcher)

report = IbEstonia::TaxReport.new(trades)
report.print
